const universities = [
    {
        name: "Stanford University",
        image: "https://via.placeholder.com/150",
        link: "https://www.stanford.edu",
        admissionRate: "4%",
        location: "California, USA",
        cost: "$53,529 per year",
        timeToDegree: "4 years",
        description: "Renowned for technology, engineering, and business programs.",
        focus: ["Engineering", "Business", "Sciences"],
    },
    {
        name: "University of Oxford",
        image: "https://via.placeholder.com/150",
        link: "https://www.ox.ac.uk",
        admissionRate: "17%",
        location: "Oxford, England",
        cost: "£9,250 (UK students), £26,770–£37,510 (international students)",
        timeToDegree: "3-4 years",
        description: "World-class education and research opportunities.",
        focus: ["Arts", "Sciences", "Business"],
    },
    {
        name: "University of Tokyo",
        image: "https://via.placeholder.com/150",
        link: "https://www.u-tokyo.ac.jp",
        admissionRate: "21%",
        location: "Tokyo, Japan",
        cost: "¥535,800 per year",
        timeToDegree: "4 years",
        description: "Japan's leading university, excelling in science and humanities.",
        focus: ["Sciences", "Engineering", "Arts"],
    },
    {
        name: "ETH Zurich",
        image: "https://via.placeholder.com/150",
        link: "https://ethz.ch",
        admissionRate: "27%",
        location: "Zurich, Switzerland",
        cost: "$1,500 per year",
        timeToDegree: "3 years (bachelor's), 2 years (master's)",
        description: "Premier university for science, engineering, and technology.",
        focus: ["Engineering", "Sciences"],
    },
    {
        name: "University of Melbourne",
        image: "https://via.placeholder.com/150",
        link: "https://www.unimelb.edu.au",
        admissionRate: "38%",
        location: "Melbourne, Australia",
        cost: "AUD 30,000–$40,000 per year",
        timeToDegree: "3 years (bachelor's), 2 years (master's)",
        description: "Australia's top university with strong research capabilities.",
        focus: ["Arts", "Business", "Sciences"],
    },
    {
        name: "University of Cape Town",
        image: "https://via.placeholder.com/150",
        link: "https://www.uct.ac.za",
        admissionRate: "45%",
        location: "Cape Town, South Africa",
        cost: "R75,000 per year",
        timeToDegree: "3 years",
        description: "Premier university in Africa, excelling in law and commerce.",
        focus: ["Business", "Arts"],
    },
    {
        name: "National University of Singapore",
        image: "https://via.placeholder.com/150",
        link: "https://www.nus.edu.sg",
        admissionRate: "27%",
        location: "Singapore",
        cost: "SGD 15,000–$30,000 per year",
        timeToDegree: "4 years",
        description: "Asia's leading university with a global focus.",
        focus: ["Engineering", "Sciences", "Business"],
    },
    {
        name: "University of Toronto",
        image: "https://via.placeholder.com/150",
        link: "https://www.utoronto.ca",
        admissionRate: "43%",
        location: "Toronto, Canada",
        cost: "CAD 6,100–$45,000 per year",
        timeToDegree: "4 years",
        description: "Top Canadian university with diverse programs.",
        focus: ["Engineering", "Arts", "Sciences"],
    },
    {
        name: "Tsinghua University",
        image: "https://via.placeholder.com/150",
        link: "https://www.tsinghua.edu.cn",
        admissionRate: "16%",
        location: "Beijing, China",
        cost: "CNY 40,000 per year",
        timeToDegree: "4 years",
        description: "Known for its engineering and science programs.",
        focus: ["Engineering", "Sciences"],
    },
    {
        name: "University of São Paulo",
        image: "https://via.placeholder.com/150",
        link: "https://www.usp.br",
        admissionRate: "20%",
        location: "São Paulo, Brazil",
        cost: "Free for Brazilian students",
        timeToDegree: "4 years",
        description: "Latin America's top university for innovation and research.",
        focus: ["Sciences", "Arts"],
    },
    {
        name: "Technical University of Munich",
        image: "https://via.placeholder.com/150",
        link: "https://www.tum.de",
        admissionRate: "20%",
        location: "Munich, Germany",
        cost: "€144 per semester",
        timeToDegree: "3 years (bachelor's), 2 years (master's)",
        description: "Highly ranked for engineering, science, and medicine.",
        focus: ["Engineering", "Sciences"],
    },
    {
        name: "University of Auckland",
        image: "https://via.placeholder.com/150",
        link: "https://www.auckland.ac.nz",
        admissionRate: "45%",
        location: "Auckland, New Zealand",
        cost: "NZD 6,000–$30,000 per year",
        timeToDegree: "3 years",
        description: "New Zealand's leading university with strong research focus.",
        focus: ["Arts", "Sciences", "Business"],
    },
    {
        name: "Seoul National University",
        image: "https://via.placeholder.com/150",
        link: "https://en.snu.ac.kr",
        admissionRate: "24%",
        location: "Seoul, South Korea",
        cost: "KRW 6,000,000 per year",
        timeToDegree: "4 years",
        description: "South Korea's top university with a global research reputation.",
        focus: ["Engineering", "Business"],
    },
    {
        name: "University of Hong Kong",
        image: "https://via.placeholder.com/150",
        link: "https://www.hku.hk",
        admissionRate: "18%",
        location: "Hong Kong",
        cost: "HKD 42,100 per year",
        timeToDegree: "4 years",
        description: "Premier university in Asia, excelling in multiple disciplines.",
        focus: ["Sciences", "Business", "Engineering"],
    },
    {
        name: "University of British Columbia",
        image: "https://via.placeholder.com/150",
        link: "https://www.ubc.ca",
        admissionRate: "46%",
        location: "Vancouver, Canada",
        cost: "CAD 5,000–$30,000 per year",
        timeToDegree: "4 years",
        description: "A leading global university with strengths in research and innovation.",
        focus: ["Arts", "Engineering", "Sciences"],
    },
];

// Functions for processing quiz and finding the best match remain unchanged.

document.addEventListener("DOMContentLoaded", showLandingPage);
